# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Blqs888CuFb_DFqi8SYrsJfPU7RIuuDR
"""

from fastapi import FastAPI
import requests
import os

app = FastAPI()

os.environ["OPENROUTER_API_KEY"] = "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"
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

@app.get("/")
def home():
    return {"status": "running", "service": "AI Summarizer & Sentiment Analyzer"}

@app.post("/summarize")
def summarize(payload: dict):
    text = payload.get("text", "")
    if not text:
        return {"error": "No text provided."}

    prompt = f"""
Summarize the following text in:
- 3 Key Bullet Points
- 1 Sentence TL;DR Summary

Text:
{text}
"""
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }
    body = {"model": "openai/gpt-4o-mini", "messages": [{"role": "user", "content": prompt}]}

    response = requests.post(OPENROUTER_URL, json=body, headers=headers)
    try:
        return {"summary": response.json()["choices"][0]["message"]["content"]}
    except:
        return {"error": "Could not generate summary", "raw_response": response.text}

@app.post("/sentiment")
def sentiment(payload: dict):
    text = payload.get("text", "")
    if not text:
        return {"error": "No text provided."}

    prompt = f"""
Analyze the sentiment of the following text.
- Sentiment: Positive, Neutral, Negative
- Confidence (0–1)
- One-sentence explanation

Text:
{text}
"""
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }
    body = {"model": "openai/gpt-4o-mini", "messages": [{"role": "user", "content": prompt}]}

    response = requests.post(OPENROUTER_URL, json=body, headers=headers)
    try:
        return {"sentiment": response.json()["choices"][0]["message"]["content"]}
    except:
        return {"error": "Could not analyze sentiment", "raw_response": response.text}